// Type declarations for static image imports (e.g. `import portrait from "@/assets/portrait.webp"`).
// next-env.d.ts provides the same reference but is generated by `next build` and not committed,
// so a type-check on a fresh checkout (CI) would not see it.
/// <reference types="next/image-types/global" />
